Totalligent.UI/Areas/GroupLifeInsurance/Controllers/GLIMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Totalligent.UI.Areas.GroupLifeInsurance.Controllers
{
    public class GLIMasterController : Controller
    {
        // GET: GroupLifeInsurance/GLIMaster
        public ActionResult InsuranceCompanyMaster()
        {
            return View();
        }
        public ActionResult ClientMaster()
        {
            return View();
        }
        public ActionResult ProducerMaster()
        {
            return View();
        }
        public ActionResult EmployeeMaster()
        {
            return View();
        }
        public ActionResult RIMaster()
        {
            return View();
        }
        public ActionResult MedicalProviderMaster()
        {
            return View();
        }
        public ActionResult DrugMaster()
        {
            return View();
        }
        public ActionResult BenefitMaster()
        {
            return View();
        }
        


        
    }
}

Totalligent.UI/Controllers/AgentController.cs
using System;
using Totalligent.BAL;
using Totalligent.UI.Models;
using Totalligent.BusinessEntities;
using System.Web.Mvc;
using System.Web;
using System.IO;

namespace Totalligent.UI.Controllers
{
    public class AgentController : Controller
    {
        TotalligentMasterBAL objMasterBAL = new TotalligentMasterBAL();
        // GET: Agent
        public ActionResult Index()
        {
            //return View();
            return PartialView("_AgentMaster");
        }

        // GET: Agent/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Agent/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Agent/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                AgentMaster objAgentMaster = new AgentMaster
                {
                    AgentName = collection["AgentName"].ToString(),
                    //AgentCode = collection["AgentCode"].ToString(),
                    Address = collection["Address"].ToString(),
                    City = collection["City"].ToString(),
                    Zipcode = collection["Zipcode"].ToString(),
                    ContactPerson = collection["ContactPerson"].ToString(),
                    MobileNumber = collection["MobileNumber"].ToString(),
                    EmailId = collection["EmailId"].ToString(),
                };

                long returnCode = -1;
                if (objAgentMaster != null)
                {
                    returnCode = objMasterBAL.SaveAgent(objAgentMaster);
                }
                return Json(returnCode);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Agent/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Agent/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Agent/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Agent/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
       
    }
}

Totalligent.UI/Controllers/BenefitMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Totalligent.UI.Controllers
{
    public class BenefitMasterController : Controller
    {
        // GET: BenefitMaster
        public ActionResult Index()
        {
            return View();
        }

        // GET: BenefitMaster/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BenefitMaster/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BenefitMaster/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BenefitMaster/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BenefitMaster/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BenefitMaster/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BenefitMaster/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Totalligent.UI/Controllers/MedicalProviderMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Totalligent.UI.Controllers
{
    public class MedicalProviderMasterController : Controller
    {
        // GET: MedicalProviderMaster
        public ActionResult Index()
        {
            return View();
        }

        // GET: MedicalProviderMaster/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MedicalProviderMaster/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MedicalProviderMaster/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicalProviderMaster/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MedicalProviderMaster/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicalProviderMaster/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MedicalProviderMaster/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Totalligent.UI/Controllers/RIMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Totalligent.UI.Controllers
{
    public class RIMasterController : Controller
    {
        // GET: RIMaster
        public ActionResult Index()
        {
            return View();
        }

        // GET: RIMaster/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RIMaster/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RIMaster/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RIMaster/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RIMaster/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RIMaster/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RIMaster/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Totalligent.UI/Areas/GroupLifeInsurance/Views/GLIMaster/BenefitMaster.cshtml
@{
    ViewBag.Title = "BenefitMaster";
    Layout = "~/Areas/GroupLifeInsurance/Views/Shared/_Layout.cshtml";
}

<h2>BenefitMaster</h2>

Totalligent.UI/Areas/GroupLifeInsurance/Views/GLIMaster/DrugMaster.cshtml
@model Totalligent.BusinessEntities.DrugMaster
@{
    ViewBag.Title = "DrugMaster";
    Layout = "~/Areas/GroupLifeInsurance/Views/Shared/_Layout.cshtml";
}


<div class="form-horizontal">
    <h4>DrugMaster</h4>
    <hr />

    <div>
        @using (Html.BeginForm("BulkUpload", "Agent", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="postedFile" accept=".xls,.xlsx" />
            <input type="submit" value="Import" />
            <a href="~/Masters/DrugMaster.xlsx" download>Download Sample format</a>
        }
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DrugCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DrugCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DrugCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DrugName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DrugName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DrugName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="btnDrugMas" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
<script type="text/javascript">

    $(function () {
        $('#btnDrugMas').click(function (e) {
            e.preventDefault();
            var formData = new FormData();
            formData.append("DrugCode", $("#DrugCode").val());
            formData.append("DrugName", $("#DrugName").val());


            $.ajax({
                type: "POST",
                url: "/Drug/Create",
                data: formData,
                dataType: "json",
                // contentType: 'application/json;charset=utf-8',
                cache: false,
                contentType: false,
                processData: false,
                success: function (res) {
                    if (res > 0) {
                        $('#dialogClient').data("kendoDialog").open();
                        $("#lblMessage").html('Insurance Company Registered Successfully.!');
                    }
                    else {
                        $('#dialogClient').data("kendoDialog").open();
                        $("#lblMessage").html('Insurance Company not Registered Successfully.!');
                    }
                },
                error: function () {
                    $("#lblMessage").html('Error while Registring the Insurance Company!.');
                }
            })
        })
    });
</script>